# Copyright (C) 2023 Solution Libre <contact@solution-libre.fr>
# 
# This file is part of GitLab with Docker Compose.
# 
# GitLab with Docker Compose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# GitLab with Docker Compose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GitLab with Docker Compose.  If not, see <https://www.gnu.org/licenses/>.

services:
  web:
    # Traefik labels are suggested as an example for people using Traefik,
    # remove them if you are using another reverse proxy.
    labels:
      traefik.http.routers.gitlab-registry.entrypoints: websecure
      traefik.http.routers.gitlab-registry.rule: "Host(`${REGISTRY_SUBDOMAIN}.${DOMAIN}`)"
      traefik.http.routers.gitlab-registry.service: gitlab-registry
      traefik.http.routers.gitlab-registry.tls.certresolver: myresolver
      traefik.http.services.gitlab-registry.loadbalancer.server.port: 5000
