version: "3.3"

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${GITLAB_HOSTNAME}"
        nginx['listen_port'] = '80'
        nginx['listen_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    labels:
      traefik.backend: 'gitlab'
      traefik.enable: 'true'
      traefik.docker.network: 'web'
      traefik.frontend.rule: "Host:${GITLAB_HOSTNAME}"
      traefik.port: '80'
    networks:
      - default
      - web
    ports:
      - ${GITLAB_SSH_PORT}:22
    volumes:
      - web_config:/etc/gitlab
      - web_logs:/var/log/gitlab
      - web_data:/var/opt/gitlab

  runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web:
    external: true

volumes:
  runner_config:
  web_config:
  web_data:
  web_logs:
