version: "3.3"

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOSTNAME}"
    labels:
      traefik.backend: 'gitlab'
      traefik.enable: 'true'
      traefik.docker.network: 'web'
      traefik.frontend.rule: "Host:${GITLAB_HOSTNAME}"
      traefik.port: '80'
    networks:
      - default
      - web
    ports:
      - '22:22'
    volumes:
      - ./docker-volume/web/config:/etc/gitlab
      - ./docker-volume/web/logs:/var/log/gitlab
      - ./docker-volume/web/data:/var/opt/gitlab

  runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - ./docker-volume/runner/config:/etc/gitlab-runner

networks:
  web:
    external: true
