version: "3.3"

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOSTNAME}"
    labels:
      traefik.backend: 'gitlab'
      traefik.enable: 'true'
      traefik.docker.network: 'web'
      traefik.frontend.rule: "Host:${GITLAB_HOSTNAME}"
      traefik.port: '80'
    networks:
      - web
    ports:
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'

networks:
  web:
    external: true
