# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check-docker-compose-syntax:
    runs-on: ubuntu-latest
    container: 
      image: docker/compose:1.28.2
    steps:
      - uses: actions/checkout@v2
      - name: Check Docker Compose file syntax
        run: docker-compose --env-file .env.dist config -q
  check-readme-syntax:
    runs-on: ubuntu-latest
    container: 
      image: markdownlint/markdownlint
    steps:
      - uses: actions/checkout@v2
      - name: Check README syntax
        run: mdl README.md
